# http://travis-ci.org/#!/2comms/pymechanize
language: python
python:
    - "3.3"
    - '3.4'
    - '3.5'
    - pypy
    - pypy3

env:
  - PYMECHANIZE=0.3

before_install:
- travis_retry sudo apt-get update
- travis_retry sudo apt-get autoremove
- travis_retry sudo apt-get autoclean
- travis_retry sudo apt-get install mongodb-org-server

install:
- travis_retry pip install --upgrade pip
- travis_retry pip install --upgrade nose
- travis_retry pip install --upgrade setuptools
- travis_retry pip install tox>=1.9
- travis_retry tox -e $(echo py$TRAVIS_PYTHON_VERSION-pymech$PYMECHANIZE | tr -d . | sed -e 's/pypypy/pypy/') -- -e test

script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION-pymech$PYMECHANIZE | tr -d . | sed -e 's/pypypy/pypy/') -- --with-coverage

branches:
  only:
    - master
    - devel
